services:
  - type: web
    name: ani-web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true